### ISSUE TITLE
Demultiplexing Part 2 Peer Review

### ISSUE THREAD

**Issue by AnnaGraceWelch** [Farrisdt/Demultiplex#1]
`if both index1 and 2 are found in indexs dictionary:`

Since the files are so large, it may be helpful to first check if there is an N in either of the indexes, and go ahead and output those to the unknown files. The way you have it should catch it and put it in the correct file; it just may take more time since it is going to have to check each item in your list of known indexes instead of just looking at the index, seeing the N, putting it in the correct file, and moving on. 

`if both indexs quality score are above quality cutoff:`

Do you mean just the index's quality scores or are you also checking the read pair's quality scores? 
Also, I believe you summed all the quality scores for the read, but you didn't find the average yet. So, if your cutoff is based on an average quality score, you may want to add that. Additionally, you may theoretically end up with less than 52 files if all of one index pairs reads are too low quality, so just something to keep in mind when troubleshooting. 

`write to unknown file (due to failing quality score)
                    add 1 to the third index of the list in the index dict`

It may be useful to just increment a variable as a counter for the unknown indexes to save time since they are not in our known indexes list. I don't think we need to track how many times each unknown one shows up since they're likely due to error. 

I hope I understood everything you had written, but if I did not, a thousand apologies! You really did a wonderful job; it was difficult to find issues!

**Comment by Farrisdt** [comment]
Hi Anna Grace, this is great feedback.

- That's a good idea to check for N first, it will probably speed things up a bit. I'll definitely be implementing that. 
- As for the quality score, I was just planning on checking the index. Per my understanding, this program should be evaluating the indexes only, sequence quality is a separate issue. I am basing it on an average, I'll be sure to note that. 
- I should output all 52 files, but yes some may be empty if the data quality is very low.
- You're correct that the unknown/misaligned should be counted separately. I was planning on having a variable, but now I am wondering if I should include them in the dictionary. Thanks for drawing it to my attention!
