### ISSUE TITLE
Ike S feedback

### ISSUE THREAD

**Issue by Ike-Sanderson** [Farrisdt/Demultiplex#3]
Farris I got several ideas from reading your algorithm- I really like the way it's organized and how you cover your bases.

```
make input upper case and error if not DNA (any char but ACTGN)
```
For example, this is such good error prevention

```
due to failing quality score)
```
also this. I tried taking a stab at a value in my algorithm but it was just a guess. How will you know what value to set as the cutoff? (not an "issue" just a pin to mark a conversation for us later)

```
report out the variables stored in the index dict. (the number of read-pairs for each type of file)
```
This is so much simpler and elegant than my system of, like, 6 loops with counters. Count it all at the end not the middle. makes more sense. I like it.

I wish I could give you more critique that was aimed at improving your code, but I like what I see.

**Comment by Farrisdt** [comment]
Thanks Ike! As for the quality score cutoff, I think that will be a case by case basis and reliant on statistics and overall data quality. I am planning to have the user pass in the value with argparse.
